INSERT INTO categories
            (user_id,
             group_id,
             NAME)
VALUES      
-- Автомобіль
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Автомобіль' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Бензин' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Автомобіль' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Інше' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Автомобіль' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Мийка' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Автомобіль' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'КАСКО 2023' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Автомобіль' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Green Card' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Автомобіль' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Vignette' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Автомобіль' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Parking' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Автомобіль' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'КАСКО' ),

-- Благодійність
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Благодійність' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'ЗСУ' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Благодійність' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Різне' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Благодійність' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Батьки' ),

-- Життя
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Продукти' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Квартира' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Комуналка' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Комуналка (батьки)' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Одяг' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'VZP' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Побут' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Дитяче' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Алкоголь' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Ремонт' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Життя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Страхування' ),

-- Здоров'я
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Здоровʼя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Аптека' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Здоровʼя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Лікарі' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Здоровʼя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Гігієна' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Здоровʼя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Аналізи' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Здоровʼя' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Різне' ),

-- Кредити
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Кредити' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Авто (extra)' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Кредити' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Авто (min)' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Кредити' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'На КАСКО' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Кредити' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Comfy' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Кредити' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Privat розтрочка' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Кредити' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Юра' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Кредити' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Rozetka' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Кредити' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Mono розстрочка' ),

-- Освіта
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Математика' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Українська' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Школа Марк' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Садок' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Чеська' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Різне' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Садок Аліса' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Школа Дмитрик' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Менталка' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Садок Аліса Extra' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Школа Марк Extra' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Логопед' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Освіта' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Prometheus' ),

-- Охорона
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Охорона' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Sheriff' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Охорона' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Prizrak' ),

-- Податки
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Податки' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'ЄП' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Податки' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'ЄСВ' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Податки' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Інше' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Податки' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'ВЗ' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Податки' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Земля' ),

-- Послуги
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Інше' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'YouTube' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Мобільний' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Lanet' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  '1Password' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Apple Music' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Digital Ocean' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Portmone' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Apple iCloud' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'AWS' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Apple One' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Домофон' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'ChatGPT' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Vodafone' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Adobe' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Copilot' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Movies' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Послуги' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Domains' ),

-- Різне
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Інше' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Кафе' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'ДР Kapowai' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Розваги' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Ресторани' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Краса' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Спорт' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Games' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Olena' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Транспорт' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Книги' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Хокей' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'На Прагу' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Іграшки' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Zoo' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Dancing' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Волейбол' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Малювання' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Йога' ),
( (SELECT id FROM auth.users WHERE email = 'demo@mail.com'),
  (SELECT id FROM groups WHERE NAME = 'Різне' AND user_id = (SELECT id FROM auth.users WHERE email = 'demo@mail.com')),
  'Ковзанка' );