INSERT INTO currencies
  (code, name, country_name, numeric_code)
VALUES
  ('AFN', 'Afghani', 'AFGHANISTAN', '971'),
  ('ALL', 'Lek', 'ALBANIA', '008'),
  ('DZD', 'Algerian Dinar', 'ALGERIA', '012'),
  ('AOA', 'Kwanza', 'ANGOLA', '973'),
  ('XAD', 'Arab Accounting Dinar', 'ARAB MONETARY FUND', '396'),
  ('ARS', 'Argentine Peso', 'ARGENTINA', '032'),
  ('AMD', 'Armenian Dram', 'ARMENIA', '051'),
  ('AWG', 'Aruban Florin', 'ARUBA', '533'),
  ('AUD', 'Australian Dollar', 'AUSTRALIA', '036'),
  ('AZN', 'Azerbaijan Manat', 'AZERBAIJAN', '944'),
  ('BSD', 'Bahamian Dollar', 'BAHAMAS (THE)', '044'),
  ('BHD', 'Bahraini Dinar', 'BAHRAIN', '048'),
  ('BDT', 'Taka', 'BANGLADESH', '050'),
  ('BBD', 'Barbados Dollar', 'BARBADOS', '052'),
  ('BZD', 'Belize Dollar', 'BELIZE', '084'),
  ('BMD', 'Bermudian Dollar', 'BERMUDA', '060'),
  ('BTN', 'Ngultrum', 'BHUTAN', '064'),
  ('BOB', 'Boliviano', 'BOLIVIA (PLURINATIONAL STATE OF)', '068'),
  ('BOV', 'Mvdol', 'BOLIVIA (PLURINATIONAL STATE OF)', '984'),
  ('BAM', 'Convertible Mark', 'BOSNIA AND HERZEGOVINA', '977'),
  ('BWP', 'Pula', 'BOTSWANA', '072'),
  ('BRL', 'Brazilian Real', 'BRAZIL', '986'),
  ('BND', 'Brunei Dollar', 'BRUNEI DARUSSALAM', '096'),
  ('XOF', 'CFA Franc BCEAO', 'BURKINA FASO', '952'),
  ('BIF', 'Burundi Franc', 'BURUNDI', '108'),
  ('CVE', 'Cabo Verde Escudo', 'CABO VERDE', '132'),
  ('KHR', 'Riel', 'CAMBODIA', '116'),
  ('CAD', 'Canadian Dollar', 'CANADA', '124'),
  ('KYD', 'Cayman Islands Dollar', 'CAYMAN ISLANDS (THE)', '136'),
  ('CLF', 'Unidad de Fomento', 'CHILE', '990'),
  ('CLP', 'Chilean Peso', 'CHILE', '152'),
  ('CNY', 'Yuan Renminbi', 'CHINA', '156'),
  ('COP', 'Colombian Peso', 'COLOMBIA', '170'),
  ('COU', 'Unidad de Valor Real', 'COLOMBIA', '970'),
  ('KMF', 'Comorian Franc ', 'COMOROS (THE)', '174'),
  ('CDF', 'Congolese Franc', 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)', '976'),
  ('CRC', 'Costa Rican Colon', 'COSTA RICA', '188'),
  ('CUP', 'Cuban Peso', 'CUBA', '192'),
  ('XCG', 'Caribbean Guilder', 'CURAÇAO', '532'),
  ('CZK', 'Czech Koruna', 'CZECHIA', '203'),
  ('DKK', 'Danish Krone', 'DENMARK', '208'),
  ('DJF', 'Djibouti Franc', 'DJIBOUTI', '262'),
  ('XCD', 'East Caribbean Dollar', 'DOMINICA', '951'),
  ('DOP', 'Dominican Peso', 'DOMINICAN REPUBLIC (THE)', '214'),
  ('EGP', 'Egyptian Pound', 'EGYPT', '818'),
  ('SVC', 'El Salvador Colon', 'EL SALVADOR', '222'),
  ('ERN', 'Nakfa', 'ERITREA', '232'),
  ('SZL', 'Lilangeni', 'ESWATINI', '748'),
  ('ETB', 'Ethiopian Birr', 'ETHIOPIA', '230'),
  ('EUR', 'Euro', 'EU', '978'),
  ('FKP', 'Falkland Islands Pound', 'FALKLAND ISLANDS (THE) [MALVINAS]', '238'),
  ('FJD', 'Fiji Dollar', 'FIJI', '242'),
  ('XPF', 'CFP Franc', 'FRENCH POLYNESIA', '953'),
  ('GMD', 'Dalasi', 'GAMBIA (THE)', '270'),
  ('GEL', 'Lari', 'GEORGIA', '981'),
  ('GHS', 'Ghana Cedi', 'GHANA', '936'),
  ('GIP', 'Gibraltar Pound', 'GIBRALTAR', '292'),
  ('GTQ', 'Quetzal', 'GUATEMALA', '320'),
  ('GNF', 'Guinean Franc', 'GUINEA', '324'),
  ('GYD', 'Guyana Dollar', 'GUYANA', '328'),
  ('HTG', 'Gourde', 'HAITI', '332'),
  ('HNL', 'Lempira', 'HONDURAS', '340'),
  ('HKD', 'Hong Kong Dollar', 'HONG KONG', '344'),
  ('HUF', 'Forint', 'HUNGARY', '348'),
  ('ISK', 'Iceland Krona', 'ICELAND', '352'),
  ('INR', 'Indian Rupee', 'INDIA', '356'),
  ('IDR', 'Rupiah', 'INDONESIA', '360'),
  ('XDR', 'SDR (Special Drawing Right)', 'INTERNATIONAL MONETARY FUND (IMF)', '960'),
  ('IQD', 'Iraqi Dinar', 'IRAQ', '368'),
  ('ILS', 'New Israeli Sheqel', 'ISRAEL', '376'),
  ('JMD', 'Jamaican Dollar', 'JAMAICA', '388'),
  ('JPY', 'Yen', 'JAPAN', '392'),
  ('JOD', 'Jordanian Dinar', 'JORDAN', '400'),
  ('KZT', 'Tenge', 'KAZAKHSTAN', '398'),
  ('KES', 'Kenyan Shilling', 'KENYA', '404'),
  ('KRW', 'Won', 'KOREA (THE REPUBLIC OF)', '410'),
  ('KWD', 'Kuwaiti Dinar', 'KUWAIT', '414'),
  ('KGS', 'Som', 'KYRGYZSTAN', '417'),
  ('LAK', 'Lao Kip', 'LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)', '418'),
  ('LBP', 'Lebanese Pound', 'LEBANON', '422'),
  ('LSL', 'Loti', 'LESOTHO', '426'),
  ('LRD', 'Liberian Dollar', 'LIBERIA', '430'),
  ('LYD', 'Libyan Dinar', 'LIBYA', '434'),
  ('CHF', 'Swiss Franc', 'LIECHTENSTEIN', '756'),
  ('MOP', 'Pataca', 'MACAO', '446'),
  ('MGA', 'Malagasy Ariary', 'MADAGASCAR', '969'),
  ('MWK', 'Malawi Kwacha', 'MALAWI', '454'),
  ('MYR', 'Malaysian Ringgit', 'MALAYSIA', '458'),
  ('MVR', 'Rufiyaa', 'MALDIVES', '462'),
  ('MRU', 'Ouguiya', 'MAURITANIA', '929'),
  ('MUR', 'Mauritius Rupee', 'MAURITIUS', '480'),
  ('MXN', 'Mexican Peso', 'MEXICO', '484'),
  ('MXV', 'Mexican Unidad de Inversion (UDI)', 'MEXICO', '979'),
  ('MDL', 'Moldovan Leu', 'MOLDOVA (THE REPUBLIC OF)', '498'),
  ('MNT', 'Tugrik', 'MONGOLIA', '496'),
  ('MAD', 'Moroccan Dirham', 'MOROCCO', '504'),
  ('MZN', 'Mozambique Metical', 'MOZAMBIQUE', '943'),
  ('MMK', 'Kyat', 'MYANMAR', '104'),
  ('NAD', 'Namibia Dollar', 'NAMIBIA', '516'),
  ('NPR', 'Nepalese Rupee', 'NEPAL', '524'),
  ('NZD', 'New Zealand Dollar', 'NEW ZEALAND', '554'),
  ('NIO', 'Cordoba Oro', 'NICARAGUA', '558'),
  ('NGN', 'Naira', 'NIGERIA', '566'),
  ('MKD', 'Denar', 'NORTH MACEDONIA', '807'),
  ('NOK', 'Norwegian Krone', 'NORWAY', '578'),
  ('OMR', 'Rial Omani', 'OMAN', '512'),
  ('PKR', 'Pakistan Rupee', 'PAKISTAN', '586'),
  ('PAB', 'Balboa', 'PANAMA', '590'),
  ('PGK', 'Kina', 'PAPUA NEW GUINEA', '598'),
  ('PYG', 'Guarani', 'PARAGUAY', '600'),
  ('PEN', 'Sol', 'PERU', '604'),
  ('PHP', 'Philippine Peso', 'PHILIPPINES (THE)', '608'),
  ('PLN', 'Zloty', 'POLAND', '985'),
  ('QAR', 'Qatari Rial', 'QATAR', '634'),
  ('RON', 'Romanian Leu', 'ROMANIA', '946'),
  ('RWF', 'Rwanda Franc', 'RWANDA', '646'),
  ('SHP', 'Saint Helena Pound', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', '654'),
  ('WST', 'Tala', 'SAMOA', '882'),
  ('STN', 'Dobra', 'SAO TOME AND PRINCIPE', '930'),
  ('SAR', 'Saudi Riyal', 'SAUDI ARABIA', '682'),
  ('RSD', 'Serbian Dinar', 'SERBIA', '941'),
  ('SCR', 'Seychelles Rupee', 'SEYCHELLES', '690'),
  ('SLE', 'Leone', 'SIERRA LEONE', '925'),
  ('SGD', 'Singapore Dollar', 'SINGAPORE', '702'),
  ('SBD', 'Solomon Islands Dollar', 'SOLOMON ISLANDS', '090'),
  ('SOS', 'Somali Shilling', 'SOMALIA', '706'),
  ('ZAR', 'Rand', 'SOUTH AFRICA', '710'),
  ('SSP', 'South Sudanese Pound', 'SOUTH SUDAN', '728'),
  ('LKR', 'Sri Lanka Rupee', 'SRI LANKA', '144'),
  ('SDG', 'Sudanese Pound', 'SUDAN (THE)', '938'),
  ('SRD', 'Surinam Dollar', 'SURINAME', '968'),
  ('SEK', 'Swedish Krona', 'SWEDEN', '752'),
  ('CHW', 'WIR Franc', 'SWITZERLAND', '948'),
  ('SYP', 'Syrian Pound', 'SYRIAN ARAB REPUBLIC', '760'),
  ('TWD', 'New Taiwan Dollar', 'TAIWAN (PROVINCE OF CHINA)', '901'),
  ('TJS', 'Somoni', 'TAJIKISTAN', '972'),
  ('TZS', 'Tanzanian Shilling', 'TANZANIA, UNITED REPUBLIC OF', '834'),
  ('THB', 'Baht', 'THAILAND', '764'),
  ('TOP', 'Pa’anga', 'TONGA', '776'),
  ('TTD', 'Trinidad and Tobago Dollar', 'TRINIDAD AND TOBAGO', '780'),
  ('TND', 'Tunisian Dinar', 'TUNISIA', '788'),
  ('TRY', 'Turkish Lira', 'TÜRKİYE', '949'),
  ('TMT', 'Turkmenistan New Manat', 'TURKMENISTAN', '934'),
  ('UGX', 'Uganda Shilling', 'UGANDA', '800'),
  ('UAH', 'Hryvnia', 'UKRAINE', '980'),
  ('AED', 'UAE Dirham', 'UNITED ARAB EMIRATES (THE)', '784'),
  ('GBP', 'Pound Sterling', 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)', '826'),
  ('USD', 'US Dollar', 'UNITED STATES OF AMERICA (THE)', '840'),
  ('USN', 'US Dollar (Next day)', 'UNITED STATES OF AMERICA (THE)', '997'),
  ('UYI', 'Uruguay Peso en Unidades Indexadas (UI)', 'URUGUAY', '940'),
  ('UYU', 'Peso Uruguayo', 'URUGUAY', '858'),
  ('UYW', 'Unidad Previsional', 'URUGUAY', '927'),
  ('UZS', 'Uzbekistan Sum', 'UZBEKISTAN', '860'),
  ('VUV', 'Vatu', 'VANUATU', '548'),
  ('VED', 'Bolívar Soberano', 'VENEZUELA (BOLIVARIAN REPUBLIC OF)', '926'),
  ('VES', 'Bolívar Soberano', 'VENEZUELA (BOLIVARIAN REPUBLIC OF)', '928'),
  ('VND', 'Dong', 'VIET NAM', '704'),
  ('ZMW', 'Zambian Kwacha', 'ZAMBIA', '967'),
  ('ZWG', 'Zimbabwe Gold', 'ZIMBABWE', '924'),
  ('XPD', 'Palladium', 'ZZ09_Palladium', '964');