import { signalStore, withMethods, withState } from '@ngrx/signals';
import { Transaction } from '@models/transactions';

type AppState = {
  transactions: Transaction[];
};

const initialState: AppState = {
  transactions: [
    {
      id: 1,
      date: '2024-06-01T12:34:56',
      group: 'Life dfdff fdfdfdf df',
      category: 'Products dfkdjfkdjf jdfkj kjdfkj  f',
      transactionAmount: 13200.1878997,
      transactionCurrency: 'USD',
      chargedAmount: 22232.4399876,
      chargedCurrency: 'UAH',
      exchangeRate: 2.333,
      description: 'Grocery Store',
      isIncome: false,
    },
    {
      id: 2,
      date: '2024-06-02T09:15:12',
      group: 'Home',
      category: 'Utilities',
      transactionAmount: 128.72,
      transactionCurrency: 'CZK',
      chargedAmount: 32.15,
      chargedCurrency: 'EUR',
      exchangeRate: 0.91689898,
      description: 'Monthly electricity and service fees',
      isIncome: false,
    },
    {
      id: 3,
      date: '2024-06-03T18:40:03',
      group: 'Travel',
      category: 'Transport',
      transactionAmount: 12.3,
      transactionCurrency: 'UAH',
      chargedAmount: 122.3,
      chargedCurrency: 'UAH',
      exchangeRate: 1,
      description: null,
      isIncome: false,
    },
    {
      id: 4,
      date: '2024-06-05T13:05:27',
      group: 'Health',
      category: 'Pharmacy',
      transactionAmount: 26.9,
      transactionCurrency: 'EUR',
      chargedAmount: 26.9,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: null,
      isIncome: false,
    },
    {
      id: 5,
      date: '2024-06-06T20:22:45',
      group: 'Education',
      category: 'Books',
      transactionAmount: 45.0,
      transactionCurrency: 'USD',
      chargedAmount: 41.05,
      chargedCurrency: 'EUR',
      exchangeRate: 8.91989822,
      description: null,
      isIncome: false,
    },
    {
      id: 6,
      date: '2024-06-07T07:58:10',
      group: 'Entertainment',
      category: 'Cinema',
      transactionAmount: 18.0,
      transactionCurrency: 'USD',
      chargedAmount: 16.43,
      chargedCurrency: 'EUR',
      exchangeRate: 0.9128,
      description: null,
      isIncome: false,
    },
    {
      id: 7,
      date: '2024-06-08T11:31:54',
      group: 'Food',
      category: 'Dining',
      transactionAmount: 27.65,
      transactionCurrency: 'EUR',
      chargedAmount: 27.65,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: null,
      isIncome: false,
    },
    {
      id: 8,
      date: '2024-06-09T16:12:33',
      group: 'Finance',
      category: 'Fees',
      transactionAmount: 9.99,
      transactionCurrency: 'EUR',
      chargedAmount: 9.99,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: null,
      isIncome: false,
    },
    {
      id: 9,
      date: '2024-06-10T10:05:21',
      group: 'Work',
      category: 'Supplies',
      transactionAmount: 32.8,
      transactionCurrency: 'USD',
      chargedAmount: 29.9,
      chargedCurrency: 'EUR',
      exchangeRate: 0.9128,
      description: 'Notebook, pens, and ergonomic mouse pad',
      isIncome: false,
    },
    {
      id: 10,
      date: '2024-06-11T19:44:08',
      group: 'Family',
      category: 'Gifts',
      transactionAmount: 60.0,
      transactionCurrency: 'EUR',
      chargedAmount: 60.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Birthday present and handwritten greeting card',
      isIncome: false,
    },
    {
      id: 11,
      date: '2024-06-12T08:27:49',
      group: 'Fitness',
      category: 'Membership',
      transactionAmount: 29.99,
      transactionCurrency: 'USD',
      chargedAmount: 27.39,
      chargedCurrency: 'EUR',
      exchangeRate: 0.913,
      description: 'Monthly gym membership with class access',
      isIncome: false,
    },
    {
      id: 12,
      date: '2024-06-13T21:18:37',
      group: 'Pets',
      category: 'Supplies',
      transactionAmount: 24.5,
      transactionCurrency: 'EUR',
      chargedAmount: 24.5,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Cat food, treats, and a new scratching mat',
      isIncome: false,
    },
    {
      id: 13,
      date: '2024-06-14T14:09:55',
      group: 'Hobbies',
      category: 'Crafts',
      transactionAmount: 15.75,
      transactionCurrency: 'USD',
      chargedAmount: 14.36,
      chargedCurrency: 'EUR',
      exchangeRate: 0.9128,
      description: 'Art supplies for weekend DIY projects',
      isIncome: false,
    },
    {
      id: 14,
      date: '2024-06-15T12:00:00',
      group: 'Travel',
      category: 'Accommodation',
      transactionAmount: 450.0,
      transactionCurrency: 'EUR',
      chargedAmount: 450.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Weekend getaway hotel booking',
      isIncome: false,
    },
    {
      id: 15,
      date: '2024-06-16T09:12:00',
      group: 'Auto',
      category: 'Registration',
      transactionAmount: 120.5,
      transactionCurrency: 'USD',
      chargedAmount: 110.3,
      chargedCurrency: 'EUR',
      exchangeRate: 0.915,
      description: null,
      isIncome: false,
    },
    {
      id: 16,
      date: '2024-06-16T18:35:10',
      group: 'Subscriptions',
      category: 'Productivity',
      transactionAmount: 12.99,
      transactionCurrency: 'EUR',
      chargedAmount: 12.99,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Monthly productivity suite subscription renewal',
      isIncome: false,
    },
    {
      id: 17,
      date: '2024-06-17T08:05:42',
      group: 'Charity',
      category: 'Relief',
      transactionAmount: 25.0,
      transactionCurrency: 'USD',
      chargedAmount: 22.85,
      chargedCurrency: 'EUR',
      exchangeRate: 0.914,
      description: null,
      isIncome: false,
    },
    {
      id: 18,
      date: '2024-06-17T21:22:05',
      group: 'Insurance',
      category: 'TravelCover',
      transactionAmount: 39.0,
      transactionCurrency: 'EUR',
      chargedAmount: 39.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: null,
      isIncome: false,
    },
    {
      id: 19,
      date: '2024-06-18T10:44:19',
      group: 'Savings',
      category: 'EmergencyFund',
      transactionAmount: 200.0,
      transactionCurrency: 'EUR',
      chargedAmount: 200.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Automated transfer to emergency savings fund',
      isIncome: false,
    },
    {
      id: 20,
      date: '2024-06-18T15:30:31',
      group: 'Taxes',
      category: 'CityTax',
      transactionAmount: 75.5,
      transactionCurrency: 'USD',
      chargedAmount: 69.1,
      chargedCurrency: 'EUR',
      exchangeRate: 0.915,
      description: 'Quarterly municipal tax payment processed online',
      isIncome: false,
    },
    {
      id: 21,
      date: '2024-06-19T07:58:55',
      group: 'Telecom',
      category: 'MobilePlan',
      transactionAmount: 22.0,
      transactionCurrency: 'EUR',
      chargedAmount: 22.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Mobile plan with extra data add-on',
      isIncome: false,
    },
    {
      id: 22,
      date: '2024-06-19T12:18:04',
      group: 'Clothing',
      category: 'Footwear',
      transactionAmount: 64.2,
      transactionCurrency: 'GBP',
      chargedAmount: 74.3,
      chargedCurrency: 'EUR',
      exchangeRate: 1.157,
      description: 'Walking shoes and weatherproof socks',
      isIncome: false,
    },
    {
      id: 23,
      date: '2024-06-20T09:40:26',
      group: 'Electronics',
      category: 'Accessories',
      transactionAmount: 18.5,
      transactionCurrency: 'USD',
      chargedAmount: 16.9,
      chargedCurrency: 'EUR',
      exchangeRate: 0.914,
      description: null,
      isIncome: false,
    },
    {
      id: 24,
      date: '2024-06-20T19:11:32',
      group: 'Beauty',
      category: 'Skincare',
      transactionAmount: 29.0,
      transactionCurrency: 'EUR',
      chargedAmount: 29.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Moisturizer and sunscreen refill bundle',
      isIncome: false,
    },
    {
      id: 25,
      date: '2024-06-21T08:55:18',
      group: 'Kids',
      category: 'School',
      transactionAmount: 42.75,
      transactionCurrency: 'EUR',
      chargedAmount: 42.75,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'School supplies and art paper pack',
      isIncome: false,
    },
    {
      id: 26,
      date: '2024-06-21T13:27:50',
      group: 'DiningOut',
      category: 'Lunch',
      transactionAmount: 19.6,
      transactionCurrency: 'EUR',
      chargedAmount: 19.6,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Quick lunch and sparkling water downtown',
      isIncome: false,
    },
    {
      id: 27,
      date: '2024-06-22T07:21:09',
      group: 'Coffee',
      category: 'Cafe',
      transactionAmount: 6.4,
      transactionCurrency: 'EUR',
      chargedAmount: 6.4,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Morning latte and croissant combo',
      isIncome: false,
    },
    {
      id: 28,
      date: '2024-06-22T16:45:41',
      group: 'Agriculture',
      category: 'Market',
      transactionAmount: 33.2,
      transactionCurrency: 'PLN',
      chargedAmount: 7.7,
      chargedCurrency: 'EUR',
      exchangeRate: 0.232,
      description: 'Local farmers market produce and herbs',
      isIncome: false,
    },
    {
      id: 29,
      date: '2024-06-23T11:09:13',
      group: 'Gardening',
      category: 'Tools',
      transactionAmount: 24.9,
      transactionCurrency: 'EUR',
      chargedAmount: 24.9,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Hand trowel and pruning shear set',
      isIncome: false,
    },
    {
      id: 30,
      date: '2024-06-23T18:33:25',
      group: 'Sports',
      category: 'Equipment',
      transactionAmount: 58.0,
      transactionCurrency: 'USD',
      chargedAmount: 53.0,
      chargedCurrency: 'EUR',
      exchangeRate: 0.9138,
      description: 'Resistance bands and training gloves',
      isIncome: false,
    },
    {
      id: 31,
      date: '2024-06-24T20:10:48',
      group: 'Events',
      category: 'Tickets',
      transactionAmount: 45.0,
      transactionCurrency: 'EUR',
      chargedAmount: 45.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Outdoor festival day pass with seating',
      isIncome: false,
    },
    {
      id: 32,
      date: '2024-06-25T07:34:59',
      group: 'Music',
      category: 'Lessons',
      transactionAmount: 35.0,
      transactionCurrency: 'EUR',
      chargedAmount: 35.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Private guitar lesson for skill building',
      isIncome: false,
    },
    {
      id: 33,
      date: '2024-06-25T22:05:36',
      group: 'Streaming',
      category: 'Video',
      transactionAmount: 14.99,
      transactionCurrency: 'USD',
      chargedAmount: 13.7,
      chargedCurrency: 'EUR',
      exchangeRate: 0.914,
      description: 'Video streaming plan with family sharing',
      isIncome: false,
    },
    {
      id: 34,
      date: '2024-06-26T09:22:11',
      group: 'Software',
      category: 'Licenses',
      transactionAmount: 79.0,
      transactionCurrency: 'USD',
      chargedAmount: 72.2,
      chargedCurrency: 'EUR',
      exchangeRate: 0.914,
      description: 'Annual license for design software update',
      isIncome: false,
    },
    {
      id: 35,
      date: '2024-06-26T14:57:03',
      group: 'Hardware',
      category: 'Peripherals',
      transactionAmount: 99.0,
      transactionCurrency: 'EUR',
      chargedAmount: 99.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Mechanical keyboard with quiet switches',
      isIncome: false,
    },
    {
      id: 36,
      date: '2024-06-27T10:12:27',
      group: 'Office',
      category: 'Printing',
      transactionAmount: 11.5,
      transactionCurrency: 'EUR',
      chargedAmount: 11.5,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Print and binding for project documents',
      isIncome: false,
    },
    {
      id: 37,
      date: '2024-06-27T18:46:52',
      group: 'Logistics',
      category: 'Shipping',
      transactionAmount: 8.75,
      transactionCurrency: 'USD',
      chargedAmount: 8.0,
      chargedCurrency: 'EUR',
      exchangeRate: 0.914,
      description: 'Parcel shipping for small online order',
      isIncome: false,
    },
    {
      id: 38,
      date: '2024-06-28T08:03:40',
      group: 'Rent',
      category: 'Apartment',
      transactionAmount: 950.0,
      transactionCurrency: 'EUR',
      chargedAmount: 950.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Monthly apartment rent via bank transfer',
      isIncome: false,
    },
    {
      id: 39,
      date: '2024-06-28T16:29:14',
      group: 'Mortgage',
      category: 'Interest',
      transactionAmount: 420.0,
      transactionCurrency: 'EUR',
      chargedAmount: 420.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Mortgage interest payment for June cycle',
      isIncome: false,
    },
    {
      id: 40,
      date: '2024-06-29T09:48:29',
      group: 'Investments',
      category: 'IndexFund',
      transactionAmount: 150.0,
      transactionCurrency: 'EUR',
      chargedAmount: 150.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Automated purchase of global index fund',
      isIncome: false,
    },
    {
      id: 41,
      date: '2024-06-29T13:37:02',
      group: 'Medical',
      category: 'Checkup',
      transactionAmount: 65.0,
      transactionCurrency: 'EUR',
      chargedAmount: 65.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Routine medical checkup appointment fee',
      isIncome: false,
    },
    {
      id: 42,
      date: '2024-06-30T11:23:17',
      group: 'Dental',
      category: 'Cleaning',
      transactionAmount: 80.0,
      transactionCurrency: 'EUR',
      chargedAmount: 80.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Dental cleaning and preventive consultation',
      isIncome: false,
    },
    {
      id: 43,
      date: '2024-06-30T19:08:51',
      group: 'Vision',
      category: 'Eyewear',
      transactionAmount: 120.0,
      transactionCurrency: 'USD',
      chargedAmount: 109.7,
      chargedCurrency: 'EUR',
      exchangeRate: 0.914,
      description: 'Prescription lenses replacement service',
      isIncome: false,
    },
    {
      id: 44,
      date: '2024-07-01T08:49:36',
      group: 'Groceries',
      category: 'Pantry',
      transactionAmount: 54.3,
      transactionCurrency: 'EUR',
      chargedAmount: 54.3,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Pantry restock with grains and spices',
      isIncome: false,
    },
    {
      id: 45,
      date: '2024-07-01T12:14:07',
      group: 'Snacks',
      category: 'Vending',
      transactionAmount: 3.2,
      transactionCurrency: 'EUR',
      chargedAmount: 3.2,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Afternoon snack and bottled water',
      isIncome: false,
    },
    {
      id: 46,
      date: '2024-07-02T06:55:22',
      group: 'TravelLocal',
      category: 'Taxi',
      transactionAmount: 14.8,
      transactionCurrency: 'EUR',
      chargedAmount: 14.8,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Early morning taxi to the train station',
      isIncome: false,
    },
    {
      id: 47,
      date: '2024-07-02T21:31:00',
      group: 'TravelInternational',
      category: 'Flight',
      transactionAmount: 320.0,
      transactionCurrency: 'USD',
      chargedAmount: 292.6,
      chargedCurrency: 'EUR',
      exchangeRate: 0.914,
      description: 'One-way flight ticket with cabin bag',
      isIncome: false,
    },
    {
      id: 48,
      date: '2024-07-03T09:05:18',
      group: 'Parking',
      category: 'Garage',
      transactionAmount: 12.0,
      transactionCurrency: 'EUR',
      chargedAmount: 12.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'City garage parking for two hours',
      isIncome: false,
    },
    {
      id: 49,
      date: '2024-07-03T17:44:09',
      group: 'Fuel',
      category: 'Diesel',
      transactionAmount: 47.5,
      transactionCurrency: 'EUR',
      chargedAmount: 47.5,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Fuel refill at highway service station',
      isIncome: false,
    },
    {
      id: 50,
      date: '2024-07-04T08:28:53',
      group: 'Maintenance',
      category: 'Service',
      transactionAmount: 210.0,
      transactionCurrency: 'EUR',
      chargedAmount: 210.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Vehicle service with oil and filter change',
      isIncome: false,
    },
    {
      id: 51,
      date: '2024-07-04T19:16:37',
      group: 'Cleaning',
      category: 'HomeCare',
      transactionAmount: 28.0,
      transactionCurrency: 'EUR',
      chargedAmount: 28.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Eco-friendly cleaning supplies refill pack',
      isIncome: false,
    },
    {
      id: 52,
      date: '2024-07-05T07:50:29',
      group: 'Laundry',
      category: 'Service',
      transactionAmount: 16.4,
      transactionCurrency: 'EUR',
      chargedAmount: 16.4,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Laundry service with folded delivery',
      isIncome: false,
    },
    {
      id: 53,
      date: '2024-07-05T13:41:58',
      group: 'Furniture',
      category: 'Decor',
      transactionAmount: 89.0,
      transactionCurrency: 'EUR',
      chargedAmount: 89.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Table lamp and minimalist wall shelves',
      isIncome: false,
    },
    {
      id: 54,
      date: '2024-07-06T10:19:44',
      group: 'Appliances',
      category: 'Kitchen',
      transactionAmount: 130.0,
      transactionCurrency: 'USD',
      chargedAmount: 118.8,
      chargedCurrency: 'EUR',
      exchangeRate: 0.914,
      description: 'Compact blender and storage containers',
      isIncome: false,
    },
    {
      id: 55,
      date: '2024-07-06T18:27:36',
      group: 'Photography',
      category: 'Printing',
      transactionAmount: 22.5,
      transactionCurrency: 'EUR',
      chargedAmount: 22.5,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Photo prints for family album update',
      isIncome: false,
    },
    {
      id: 56,
      date: '2024-07-07T09:36:12',
      group: 'Books',
      category: 'Audiobooks',
      transactionAmount: 9.5,
      transactionCurrency: 'USD',
      chargedAmount: 8.7,
      chargedCurrency: 'EUR',
      exchangeRate: 0.915,
      description: 'Audiobook purchase for commute listening',
      isIncome: false,
    },
    {
      id: 57,
      date: '2024-07-07T20:05:55',
      group: 'Courses',
      category: 'Online',
      transactionAmount: 59.0,
      transactionCurrency: 'EUR',
      chargedAmount: 59.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Online course on data visualization basics',
      isIncome: false,
    },
    {
      id: 58,
      date: '2024-07-08T08:11:39',
      group: 'Conferences',
      category: 'Pass',
      transactionAmount: 180.0,
      transactionCurrency: 'EUR',
      chargedAmount: 180.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Conference pass with workshops access',
      isIncome: false,
    },
    {
      id: 59,
      date: '2024-07-08T15:26:04',
      group: 'Donations',
      category: 'Community',
      transactionAmount: 15.0,
      transactionCurrency: 'EUR',
      chargedAmount: 15.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Neighborhood community support contribution',
      isIncome: false,
    },
    {
      id: 60,
      date: '2024-07-09T07:58:23',
      group: 'Security',
      category: 'Monitoring',
      transactionAmount: 19.99,
      transactionCurrency: 'USD',
      chargedAmount: 18.3,
      chargedCurrency: 'EUR',
      exchangeRate: 0.915,
      description: 'Home security monitoring monthly fee',
      isIncome: false,
    },
    {
      id: 61,
      date: '2024-07-09T18:12:47',
      group: 'Banking',
      category: 'Transfer',
      transactionAmount: 5.0,
      transactionCurrency: 'EUR',
      chargedAmount: 5.0,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'International transfer service charge',
      isIncome: false,
    },
    {
      id: 62,
      date: '2024-07-10T09:33:30',
      group: 'UtilitiesGas',
      category: 'Gas',
      transactionAmount: 31.6,
      transactionCurrency: 'EUR',
      chargedAmount: 31.6,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Monthly gas bill with usage summary',
      isIncome: false,
    },
    {
      id: 63,
      date: '2024-07-10T20:21:16',
      group: 'UtilitiesWater',
      category: 'Water',
      transactionAmount: 18.4,
      transactionCurrency: 'EUR',
      chargedAmount: 18.4,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Water utility bill for household usage',
      isIncome: false,
    },
    {
      id: 64,
      date: '2024-07-11T10:47:05',
      group: 'Utilities Internet',
      category: 'Broadband',
      transactionAmount: 27.99,
      transactionCurrency: 'EUR',
      chargedAmount: 27.99,
      chargedCurrency: 'EUR',
      exchangeRate: 1,
      description: 'Home broadband plan with router rental',
      isIncome: false,
    },
  ],
};

export const AppStore = signalStore(
  { providedIn: 'root' },
  withState(initialState),
  withMethods((store) => ({})),
);
