CREATE TYPE account_type AS ENUM ('regular', 'savings_goal');

create table public.accounts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  user_id uuid not null default auth.uid (),
  currency_id bigint not null,
  updated_at timestamp with time zone null,
  type public.account_type not null default 'regular'::account_type,
  constraint accounts_pkey primary key (id),
  constraint accounts_user_id_fkey foreign KEY (user_id) references auth.users (id),
  constraint accounts_currency_id_fkey foreign KEY (currency_id) references currencies (id),
  constraint accounts_name_check check ((length(name) <= 30))
);

ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;

create policy "Enable users to view their own data only"
on "public"."accounts"
as PERMISSIVE
for SELECT
to authenticated
using (
  (( SELECT auth.uid() AS uid) = user_id)
);

create policy "Enable insert for users based on user_id"
on "public"."accounts"
as PERMISSIVE
for INSERT
to public
with check (
  (select auth.uid()) = user_id
);

create trigger before_update_account_trigger BEFORE
update on accounts for EACH row
execute FUNCTION storage.update_updated_at_column ();