create table public.currencies (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  code text not null,
  country_name text not null,
  numeric_code smallint not null,
  name text not null,
  constraint currencies_pkey primary key (id),
  constraint currencies_code_key unique (code),
  constraint currencies_code_check check ((code ~ '^[A-Z]{3}$'::text)),
  constraint currencies_name_check check ((length(name) < 50))
);

ALTER TABLE currencies ENABLE ROW LEVEL SECURITY;

create policy "Enable read access for all users"
on "public"."currencies"
as PERMISSIVE
for SELECT
to public
using (
  true
);