create table public.groups (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  user_id uuid not null default auth.uid (),
  is_system boolean not null default false,
  constraint groups_pkey primary key (id),
  constraint groups_user_id_fkey foreign KEY (user_id) references auth.users (id),
  constraint groups_name_check check ((length(name) < 25))
);

ALTER TABLE groups ENABLE ROW LEVEL SECURITY;

create policy "Enable users to view their own data only"
on "public"."groups"
as PERMISSIVE
for SELECT
to authenticated
using (
  (( SELECT auth.uid() AS uid) = user_id)
);

create table public.categories (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  group_id bigint not null,
  name text not null,
  is_system boolean not null default false,
  constraint categories_pkey primary key (id),
  constraint categories_user_id_fkey foreign KEY (user_id) references auth.users (id),
  constraint categories_group_id_fkey foreign KEY (group_id) references groups (id),
  constraint categories_name_check check ((length(name) < 25))
);

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

create policy "Enable users to view their own data only"
on "public"."categories"
as PERMISSIVE
for SELECT
to authenticated
using (
  (( SELECT auth.uid() AS uid) = user_id)
);

create function create_default_user_categories()
  returns trigger
  language plpgsql
  security definer
  set search_path = ''
  as $$
  begin
    INSERT INTO public.groups (user_id, name, is_system) 
    SELECT 
        NEW.id,
        'adjustment',                                   
        true;
    INSERT INTO public.categories (user_id, group_id, name, is_system)
    SELECT
        NEW.id, 
        public.groups.id, 
        'adjustment', 
        true 
    FROM public.groups
    WHERE public.groups.user_id = NEW.id AND public.groups.name = 'adjustment';

    return NEW;
  end;
  $$;

  create trigger create_user_trigger
  after insert on auth.users
  for each row
  execute function public.create_default_user_categories();