CREATE TABLE monthly_budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NULL,
  user_id uuid NOT NULL DEFAULT auth.uid (),
  budget_month date NOT NULL DEFAULT date_trunc('month', now()::timestamp)::date,
  planned_amount NUMERIC NOT NULL,
  category_id BIGINT NOT NULL,
  currency_id BIGINT NOT NULL,
  CONSTRAINT monthly_budgets_pkey PRIMARY KEY (id),
  CONSTRAINT monthly_budgets_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id),
  CONSTRAINT monthly_budgets_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES currencies (id),
  CONSTRAINT monthly_budgets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
);

ALTER TABLE monthly_budgets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable users to view their own data only" ON "public"."monthly_budgets" AS PERMISSIVE FOR
SELECT
  TO authenticated USING (
    (
      (
        SELECT
          auth.uid () AS uid
      ) = user_id
    )
  );

CREATE POLICY "Enable insert for users based on user_id" ON "public"."monthly_budgets" AS PERMISSIVE FOR INSERT TO public
WITH
  CHECK (
    (
      SELECT
        auth.uid ()
    ) = user_id
  );

CREATE POLICY "Enable update their own data only" ON "public"."monthly_budgets" AS PERMISSIVE
FOR UPDATE
  TO authenticated USING (
    (
      user_id = (
        SELECT
          auth.uid () AS uid
      )
    )
  );

CREATE OR REPLACE FUNCTION public.set_monthly_budget_month_start () returns trigger language plpgsql
SET
  search_path = '' AS $$
begin
  if new.budget_month <> date_trunc('month', new.budget_month::timestamp)::date then
    new.budget_month := date_trunc('month', new.budget_month::timestamp)::date;
  end if;
  return new;
end;
$$;

CREATE TRIGGER before_update_monthly_budget_trigger BEFORE
UPDATE ON monthly_budgets FOR EACH ROW
EXECUTE FUNCTION storage.update_updated_at_column ();

CREATE TRIGGER before_insert_monthly_budget_trigger BEFORE
INSERT ON monthly_budgets FOR EACH ROW
EXECUTE FUNCTION public.set_monthly_budget_month_start ();

CREATE TRIGGER before_update_monthly_budget_month_trigger BEFORE
UPDATE OF budget_month ON monthly_budgets FOR EACH ROW
EXECUTE FUNCTION public.set_monthly_budget_month_start ();


CREATE OR REPLACE FUNCTION get_current_month_budgets_by_category (
  p_currency_code TEXT
) returns TABLE (
  category_name TEXT,
  total_budget NUMERIC
) language sql
SET
  search_path = '' AS $$
  select
    cat.name as category_name,
    sum(mb.planned_amount) as total_budget
  from public.monthly_budgets mb
  join public.categories cat
    on cat.id = mb.category_id
  join public.currencies cur
    on cur.id = mb.currency_id
  where cur.code = p_currency_code
    and mb.budget_month = date_trunc('month', now()::timestamp)::date
  group by cat.name
  order by total_budget desc, category_name asc;
$$;