create table public.savings_goals (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  target_date date not null,
  target_amount numeric not null,
  is_cancelled boolean not null default false,
  account_id bigint not null,
  constraint savings_goals_pkey primary key (id),
  constraint savings_goals_account_id_key unique (account_id),
  constraint savings_goals_account_id_fkey foreign KEY (account_id) references accounts (id) on delete CASCADE,
  constraint savings_goals_user_id_fkey foreign KEY (user_id) references auth.users (id)
);

ALTER TABLE savings_goals ENABLE ROW LEVEL SECURITY;

create policy "Enable users to view their own data only"
on "public"."savings_goals"
as PERMISSIVE
for SELECT
to authenticated
using (
  (( SELECT auth.uid() AS uid) = user_id)
);

create policy "Enable insert for users based on user_id"
on "public"."savings_goals"
as PERMISSIVE
for INSERT
to public
with check (
  (select auth.uid()) = user_id
);

CREATE POLICY "Enable update their own data only" ON "public"."savings_goals" AS PERMISSIVE
FOR UPDATE
  TO authenticated USING (
    (
      user_id = (
        SELECT
          auth.uid () AS uid
      )
    )
  );

create policy "Enable delete for users based on user_id"
on "public"."savings_goals"
as PERMISSIVE
for DELETE
to public
using (
  (select auth.uid()) = user_id
);


CREATE OR REPLACE FUNCTION get_savings_goals (
  p_limit INTEGER DEFAULT NULL,
  p_status public.savings_goal_status DEFAULT NULL,
  p_period_to DATE DEFAULT NULL
) RETURNS TABLE (
  id BIGINT,
  name TEXT,
  currency_code TEXT,
  target_date public.savings_goals.target_date%TYPE,
  status public.savings_goal_status,
  target_amount public.savings_goals.target_amount%TYPE,
  accumulated_amount NUMERIC
) LANGUAGE sql
STABLE
SET search_path = '' AS $$
  WITH goal_data AS (
    SELECT
      acc.id,
      acc.name,
      cur.code AS currency_code,
      sg.target_date,
      sg.target_amount,
      sg.is_cancelled,
      COALESCE(SUM(t.charged_amount), 0) AS accumulated_amount,
      acc.created_at
    FROM public.accounts acc
    JOIN public.currencies cur ON cur.id = acc.currency_id
    JOIN public.savings_goals sg ON sg.account_id = acc.id
    LEFT JOIN public.transactions t ON t.account_id = acc.id
    WHERE acc.type = 'savings_goal'::public.account_type
      AND (p_period_to IS NULL OR sg.target_date <= p_period_to)
    GROUP BY acc.id, acc.name, cur.code, sg.target_date, sg.target_amount, sg.is_cancelled, acc.created_at
  ),
  goal_with_status AS (
    SELECT
      id,
      name,
      currency_code,
      target_date,
      target_amount,
      accumulated_amount,
      created_at,
      CASE
        WHEN is_cancelled THEN 'cancelled'::public.savings_goal_status
        WHEN accumulated_amount >= target_amount THEN 'done'::public.savings_goal_status
        WHEN accumulated_amount > 0 THEN 'in_progress'::public.savings_goal_status
        ELSE 'not_started'::public.savings_goal_status
      END AS status
    FROM goal_data
  )
  SELECT id, name, currency_code, target_date, status, target_amount, accumulated_amount
  FROM goal_with_status
  WHERE (p_status IS NULL OR status = p_status)
  ORDER BY created_at DESC
  LIMIT p_limit;
$$;
