CREATE TYPE savings_goal_status AS ENUM ('not_started', 'in_progress', 'done', 'cancelled');

create table public.savings_goals (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  start_date date null,
  end_date date null,
  amount numeric not null,
  status public.savings_goal_status not null default 'not_started'::savings_goal_status,
  account_id bigint not null,
  constraint savings_goals_pkey primary key (id),
  constraint savings_goals_account_id_key unique (account_id),
  constraint savings_goals_account_id_fkey foreign KEY (account_id) references accounts (id) on delete CASCADE,
  constraint savings_goals_user_id_fkey foreign KEY (user_id) references auth.users (id)
);

ALTER TABLE savings_goals ENABLE ROW LEVEL SECURITY;

create policy "Enable users to view their own data only"
on "public"."savings_goals"
as PERMISSIVE
for SELECT
to authenticated
using (
  (( SELECT auth.uid() AS uid) = user_id)
);

create policy "Enable insert for users based on user_id"
on "public"."savings_goals"
as PERMISSIVE
for INSERT
to public
with check (
  (select auth.uid()) = user_id
);

CREATE OR REPLACE FUNCTION get_savings_goal_balances (
  p_limit INTEGER DEFAULT 20
) returns TABLE (
  id BIGINT,
  name TEXT,
  currency_code TEXT,
  start_date savings_goals.start_date % type,
  end_date savings_goals.end_date % type,
  status savings_goals.status % type,
  amount savings_goals.amount % type,
  balance NUMERIC
) language sql
SET
  search_path = '' AS $$
  select
    acc.id,
    acc.name,
    cur.code as currency_code,
    sg.start_date,
    sg.end_date,
    sg.status,
    sg.amount,
    coalesce(sum(t.account_amount), 0) as balance
  from public.accounts acc
  join public.currencies cur
    on cur.id = acc.currency_id
  join public.savings_goals sg
    on sg.account_id = acc.id
  left join public.transactions t
    on t.account_id = acc.id
  where acc.type = 'savings_goal'
  group by acc.id, acc.name, cur.code, sg.start_date, sg.end_date, sg.amount, sg.status
  order by acc.created_at desc
  limit greatest(coalesce(p_limit, 20), 1);
$$;