create table public.savings_goals (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  target_date date not null,
  target_amount numeric not null,
  is_cancelled boolean not null default false,
  is_done boolean NOT NULL DEFAULT false,
  account_id bigint not null,
  constraint savings_goals_pkey primary key (id),
  constraint savings_goals_account_id_key unique (account_id),
  constraint savings_goals_account_id_fkey foreign KEY (account_id) references accounts (id) on delete CASCADE,
  constraint savings_goals_user_id_fkey foreign KEY (user_id) references auth.users (id)
);

ALTER TABLE savings_goals ENABLE ROW LEVEL SECURITY;

create policy "Enable users to view their own data only"
on "public"."savings_goals"
as PERMISSIVE
for SELECT
to authenticated
using (
  (( SELECT auth.uid() AS uid) = user_id)
);

create policy "Enable insert for users based on user_id"
on "public"."savings_goals"
as PERMISSIVE
for INSERT
to public
with check (
  (select auth.uid()) = user_id
);

CREATE POLICY "Enable update their own data only" ON "public"."savings_goals" AS PERMISSIVE
FOR UPDATE
  TO authenticated USING (
    (
      user_id = (
        SELECT
          auth.uid () AS uid
      )
    )
  );

create policy "Enable delete for users based on user_id"
on "public"."savings_goals"
as PERMISSIVE
for DELETE
to public
using (
  (select auth.uid()) = user_id
);


CREATE OR REPLACE FUNCTION public.create_savings_goal(
  p_name text,
  p_currency_id bigint,
  p_target_amount numeric,
  p_target_date date
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_account_id bigint;
BEGIN
  INSERT INTO public.accounts (name, currency_id, type)
  VALUES (p_name, p_currency_id, 'savings_goal'::public.account_type)
  RETURNING id INTO v_account_id;

  INSERT INTO public.savings_goals (account_id, target_amount, target_date)
  VALUES (v_account_id, p_target_amount, p_target_date);

  RETURN v_account_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_savings_goal(
  p_account_id bigint,
  p_name text,
  p_target_amount numeric,
  p_target_date date
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.accounts
  SET name = p_name
  WHERE id = p_account_id
    AND type = 'savings_goal'::public.account_type;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Savings goal account % not found', p_account_id;
  END IF;

  UPDATE public.savings_goals
  SET target_amount = p_target_amount,
      target_date   = p_target_date
  WHERE account_id = p_account_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Savings goal record for account % not found', p_account_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.cancel_savings_goal(p_account_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.savings_goals
  SET is_cancelled = true
  WHERE account_id = p_account_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Savings goal for account % not found', p_account_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_savings_goal_as_done(p_account_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.savings_goals
  SET is_done = true
  WHERE account_id = p_account_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Savings goal for account % not found', p_account_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_savings_goal(p_account_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  DELETE FROM public.transactions
  WHERE account_id = p_account_id;

  DELETE FROM public.accounts
  WHERE id = p_account_id
    AND type = 'savings_goal'::public.account_type;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Savings goal account % not found', p_account_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION get_savings_goals (
  p_limit INTEGER DEFAULT NULL,
  p_status public.savings_goal_status DEFAULT NULL,
  p_period_from DATE DEFAULT NULL
) RETURNS TABLE (
  id BIGINT,
  name TEXT,
  currency_code TEXT,
  target_date public.savings_goals.target_date%TYPE,
  status public.savings_goal_status,
  target_amount public.savings_goals.target_amount%TYPE,
  accumulated_amount NUMERIC,
  has_transfers BOOLEAN
) LANGUAGE sql
STABLE
SET search_path = '' AS $$
  WITH goal_data AS (
    SELECT
      acc.id,
      acc.name,
      cur.code AS currency_code,
      sg.target_date,
      sg.target_amount,
      sg.is_cancelled,
      sg.is_done,
      COALESCE(SUM(t.charged_amount), 0) AS accumulated_amount,
      COUNT(t.id) > 0 AS has_transfers,
      acc.created_at
    FROM public.accounts acc
    JOIN public.currencies cur ON cur.id = acc.currency_id
    JOIN public.savings_goals sg ON sg.account_id = acc.id
    LEFT JOIN public.transactions t ON t.account_id = acc.id
    WHERE acc.type = 'savings_goal'::public.account_type
      AND (p_period_from IS NULL OR sg.target_date >= p_period_from)
    GROUP BY acc.id, acc.name, cur.code, sg.target_date, sg.target_amount, sg.is_cancelled, sg.is_done, acc.created_at
  ),
  goal_with_status AS (
    SELECT
      id,
      name,
      currency_code,
      target_date,
      target_amount,
      accumulated_amount,
      has_transfers,
      created_at,
      CASE
        WHEN is_cancelled THEN 'cancelled'::public.savings_goal_status
        WHEN is_done      THEN 'done'::public.savings_goal_status
        WHEN accumulated_amount > 0 THEN 'in_progress'::public.savings_goal_status
        ELSE 'not_started'::public.savings_goal_status
      END AS status
    FROM goal_data
  )
  SELECT id, name, currency_code, target_date, status, target_amount, accumulated_amount, has_transfers
  FROM goal_with_status
  WHERE (p_status IS NULL OR status = p_status)
  ORDER BY created_at DESC
  LIMIT p_limit;
$$;

CREATE OR REPLACE FUNCTION public.get_monthly_savings_overview(
  p_year          integer,
  p_currency_code text
)
RETURNS TABLE(
  month                date,
  current_year_amount  numeric,
  previous_year_amount numeric
)
LANGUAGE sql
STABLE
SET search_path TO ''
AS $function$
WITH
  months AS (
    SELECT gs::date AS month
    FROM generate_series(
      make_date(p_year, 1, 1),
      make_date(p_year, 12, 1),
      interval '1 month'
    ) AS gs
  ),
  savings_accounts AS (
    SELECT acc.id AS account_id
    FROM public.accounts acc
    JOIN public.currencies cur ON cur.id = acc.currency_id
    WHERE acc.type = 'savings_goal'::public.account_type
      AND cur.code  = p_currency_code
  ),
  current_year AS (
    SELECT
      date_trunc('month', (t.transacted_at + t.local_offset))::date AS month,
      SUM(t.charged_amount)                                          AS amount
    FROM public.transactions t
    JOIN savings_accounts sa ON sa.account_id = t.account_id
    WHERE (t.transacted_at + t.local_offset) >= make_date(p_year, 1, 1)::timestamp
      AND (t.transacted_at + t.local_offset) <  make_date(p_year + 1, 1, 1)::timestamp
    GROUP BY date_trunc('month', (t.transacted_at + t.local_offset))
  ),
  previous_year AS (
    SELECT
      (date_trunc('month', (t.transacted_at + t.local_offset))
        + interval '1 year')::date                                   AS month,
      SUM(t.charged_amount)                                          AS amount
    FROM public.transactions t
    JOIN savings_accounts sa ON sa.account_id = t.account_id
    WHERE (t.transacted_at + t.local_offset) >= make_date(p_year - 1, 1, 1)::timestamp
      AND (t.transacted_at + t.local_offset) <  make_date(p_year, 1, 1)::timestamp
    GROUP BY date_trunc('month', (t.transacted_at + t.local_offset))
  )
SELECT
  m.month,
  COALESCE(cy.amount, 0) AS current_year_amount,
  COALESCE(py.amount, 0) AS previous_year_amount
FROM months          m
LEFT JOIN current_year  cy ON cy.month = m.month
LEFT JOIN previous_year py ON py.month = m.month
ORDER BY m.month;
$function$;