CREATE TYPE transaction_type AS ENUM ('income', 'expense', 'adjustment');

create table public.transactions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  transacted_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null,
  comment text null,
  user_id uuid not null default auth.uid (),
  account_id bigint not null,
  transaction_amount numeric not null,
  transaction_currency_id bigint not null,
  account_amount numeric not null,
  account_currency_id bigint not null,
  type public.transaction_type not null default 'expense'::transaction_type,
  category_id bigint not null,
  constraint transactions_pkey primary key (id),
  constraint transactions_user_id_fkey foreign KEY (user_id) references auth.users (id),
  constraint transactions_account_id_fkey foreign KEY (account_id) references accounts (id),
  constraint transactions_transaction_currency_id_fkey foreign KEY (transaction_currency_id) references currencies (id),
  constraint transactions_account_currency_id_fkey foreign KEY (account_currency_id) references currencies (id),
  constraint transactions_category_id_fkey foreign KEY (category_id) references categories (id),
  constraint transactions_amount_currency_check check (
    (
      (transaction_currency_id <> account_currency_id)
      or (transaction_amount = account_amount)
    )
  ),
  constraint transactions_comment_check check ((length(comment) < 100))
);

ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

create policy "Enable users to view their own data only"
on "public"."transactions"
as PERMISSIVE
for SELECT
to authenticated
using (
  (( SELECT auth.uid() AS uid) = user_id)
);


create trigger before_update_transaction_trigger BEFORE
update on transactions for EACH row
execute FUNCTION storage.update_updated_at_column ();


CREATE OR REPLACE FUNCTION public.set_transaction_account_currency()
RETURNS TRIGGER 
security invoker
set search_path = ''
AS $$
BEGIN
  -- Отримуємо валюту акаунта з таблиці accounts
  SELECT currency_id INTO NEW.account_currency_id
  FROM public.accounts
  WHERE id = NEW.account_id;

  -- Перевірка: якщо акаунт не знайдено (хоча constraint має це відловити раніше)
  IF NEW.account_currency_id IS NULL THEN
    RAISE EXCEPTION 'Account with id % not found', NEW.account_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_account_currency_trigger
BEFORE INSERT ON public.transactions
FOR EACH ROW
EXECUTE FUNCTION public.set_transaction_account_currency();