create table public.monthly_budgets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  category_id bigint not null,
  user_id uuid not null default auth.uid (),
  budget_month date not null,
  planned_amount numeric not null,
  currency_id bigint not null,
  constraint monthly_budgets_pkey primary key (id),
  constraint monthly_budgets_category_id_fkey foreign KEY (category_id) references categories (id),
  constraint monthly_budgets_user_id_fkey foreign KEY (user_id) references auth.users (id),
  constraint monthly_budgets_currency_id_fkey foreign KEY (currency_id) references currencies (id)
) TABLESPACE pg_default;