create type "public"."transaction_type" as enum ('income', 'expense', 'adjustment');


  create table "public"."accounts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "user_id" uuid not null,
    "currency_id" bigint not null,
    "updated_at" timestamp with time zone
      );


alter table "public"."accounts" enable row level security;


  create table "public"."categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default gen_random_uuid(),
    "group_id" bigint not null,
    "name" text not null,
    "is_system" boolean not null default false
      );


alter table "public"."categories" enable row level security;


  create table "public"."currencies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "code" text not null,
    "country_name" text not null,
    "numeric_code" smallint not null,
    "name" text not null
      );


alter table "public"."currencies" enable row level security;


  create table "public"."groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "user_id" uuid not null default gen_random_uuid(),
    "is_system" boolean not null default false
      );


alter table "public"."groups" enable row level security;


  create table "public"."transactions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "transacted_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone,
    "comment" text,
    "user_id" uuid not null,
    "account_id" bigint not null,
    "transaction_amount" numeric not null,
    "transaction_currency_id" bigint not null,
    "account_amount" numeric not null,
    "account_currency_id" bigint not null,
    "type" public.transaction_type not null default 'expense'::public.transaction_type,
    "category_id" bigint not null
      );


alter table "public"."transactions" enable row level security;

CREATE UNIQUE INDEX accounts_pkey ON public.accounts USING btree (id);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX currencies_code_key ON public.currencies USING btree (code);

CREATE UNIQUE INDEX currencies_pkey ON public.currencies USING btree (id);

CREATE UNIQUE INDEX groups_pkey ON public.groups USING btree (id);

CREATE UNIQUE INDEX transactions_pkey ON public.transactions USING btree (id);

alter table "public"."accounts" add constraint "accounts_pkey" PRIMARY KEY using index "accounts_pkey";

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."currencies" add constraint "currencies_pkey" PRIMARY KEY using index "currencies_pkey";

alter table "public"."groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";

alter table "public"."transactions" add constraint "transactions_pkey" PRIMARY KEY using index "transactions_pkey";

alter table "public"."accounts" add constraint "accounts_currency_id_fkey" FOREIGN KEY (currency_id) REFERENCES public.currencies(id) not valid;

alter table "public"."accounts" validate constraint "accounts_currency_id_fkey";

alter table "public"."accounts" add constraint "accounts_name_check" CHECK ((length(name) < 30)) not valid;

alter table "public"."accounts" validate constraint "accounts_name_check";

alter table "public"."accounts" add constraint "accounts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."accounts" validate constraint "accounts_user_id_fkey";

alter table "public"."categories" add constraint "categories_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public.groups(id) not valid;

alter table "public"."categories" validate constraint "categories_group_id_fkey";

alter table "public"."categories" add constraint "categories_name_check" CHECK ((length(name) < 25)) not valid;

alter table "public"."categories" validate constraint "categories_name_check";

alter table "public"."categories" add constraint "categories_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."categories" validate constraint "categories_user_id_fkey";

alter table "public"."currencies" add constraint "currencies_code_check" CHECK ((code ~ '^[A-Z]{3}$'::text)) not valid;

alter table "public"."currencies" validate constraint "currencies_code_check";

alter table "public"."currencies" add constraint "currencies_code_key" UNIQUE using index "currencies_code_key";

alter table "public"."currencies" add constraint "currencies_name_check" CHECK ((length(name) < 50)) not valid;

alter table "public"."currencies" validate constraint "currencies_name_check";

alter table "public"."groups" add constraint "groups_name_check" CHECK ((length(name) < 25)) not valid;

alter table "public"."groups" validate constraint "groups_name_check";

alter table "public"."groups" add constraint "groups_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."groups" validate constraint "groups_user_id_fkey";

alter table "public"."transactions" add constraint "transactions_account_currency_id_fkey" FOREIGN KEY (account_currency_id) REFERENCES public.currencies(id) not valid;

alter table "public"."transactions" validate constraint "transactions_account_currency_id_fkey";

alter table "public"."transactions" add constraint "transactions_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) not valid;

alter table "public"."transactions" validate constraint "transactions_account_id_fkey";

alter table "public"."transactions" add constraint "transactions_amount_currency_check" CHECK (((transaction_currency_id <> account_currency_id) OR (transaction_amount = account_amount))) not valid;

alter table "public"."transactions" validate constraint "transactions_amount_currency_check";

alter table "public"."transactions" add constraint "transactions_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id) not valid;

alter table "public"."transactions" validate constraint "transactions_category_id_fkey";

alter table "public"."transactions" add constraint "transactions_comment_check" CHECK ((length(comment) < 100)) not valid;

alter table "public"."transactions" validate constraint "transactions_comment_check";

alter table "public"."transactions" add constraint "transactions_transaction_currency_id_fkey" FOREIGN KEY (transaction_currency_id) REFERENCES public.currencies(id) not valid;

alter table "public"."transactions" validate constraint "transactions_transaction_currency_id_fkey";

alter table "public"."transactions" add constraint "transactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."transactions" validate constraint "transactions_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_default_user_categories()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  begin
    INSERT INTO public.groups (user_id, name, is_system) 
    SELECT 
        NEW.id,
        'adjustment',                                   
        true;
    INSERT INTO public.categories (user_id, group_id, name, is_system)
    SELECT
        NEW.id, 
        public.groups.id, 
        'adjustment', 
        true 
    FROM public.groups
    WHERE public.groups.user_id = NEW.id AND public.groups.name = 'adjustment';

    return NEW;
  end;
  $function$
;

CREATE OR REPLACE FUNCTION public.set_transaction_account_currency()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
BEGIN
  -- Отримуємо валюту акаунта з таблиці accounts
  SELECT currency_id INTO NEW.account_currency_id
  FROM public.accounts
  WHERE id = NEW.account_id;

  -- Перевірка: якщо акаунт не знайдено (хоча constraint має це відловити раніше)
  IF NEW.account_currency_id IS NULL THEN
    RAISE EXCEPTION 'Account with id % not found', NEW.account_id;
  END IF;

  RETURN NEW;
END;
$function$
;

grant delete on table "public"."accounts" to "anon";

grant insert on table "public"."accounts" to "anon";

grant references on table "public"."accounts" to "anon";

grant select on table "public"."accounts" to "anon";

grant trigger on table "public"."accounts" to "anon";

grant truncate on table "public"."accounts" to "anon";

grant update on table "public"."accounts" to "anon";

grant delete on table "public"."accounts" to "authenticated";

grant insert on table "public"."accounts" to "authenticated";

grant references on table "public"."accounts" to "authenticated";

grant select on table "public"."accounts" to "authenticated";

grant trigger on table "public"."accounts" to "authenticated";

grant truncate on table "public"."accounts" to "authenticated";

grant update on table "public"."accounts" to "authenticated";

grant delete on table "public"."accounts" to "service_role";

grant insert on table "public"."accounts" to "service_role";

grant references on table "public"."accounts" to "service_role";

grant select on table "public"."accounts" to "service_role";

grant trigger on table "public"."accounts" to "service_role";

grant truncate on table "public"."accounts" to "service_role";

grant update on table "public"."accounts" to "service_role";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."currencies" to "anon";

grant insert on table "public"."currencies" to "anon";

grant references on table "public"."currencies" to "anon";

grant select on table "public"."currencies" to "anon";

grant trigger on table "public"."currencies" to "anon";

grant truncate on table "public"."currencies" to "anon";

grant update on table "public"."currencies" to "anon";

grant delete on table "public"."currencies" to "authenticated";

grant insert on table "public"."currencies" to "authenticated";

grant references on table "public"."currencies" to "authenticated";

grant select on table "public"."currencies" to "authenticated";

grant trigger on table "public"."currencies" to "authenticated";

grant truncate on table "public"."currencies" to "authenticated";

grant update on table "public"."currencies" to "authenticated";

grant delete on table "public"."currencies" to "service_role";

grant insert on table "public"."currencies" to "service_role";

grant references on table "public"."currencies" to "service_role";

grant select on table "public"."currencies" to "service_role";

grant trigger on table "public"."currencies" to "service_role";

grant truncate on table "public"."currencies" to "service_role";

grant update on table "public"."currencies" to "service_role";

grant delete on table "public"."groups" to "anon";

grant insert on table "public"."groups" to "anon";

grant references on table "public"."groups" to "anon";

grant select on table "public"."groups" to "anon";

grant trigger on table "public"."groups" to "anon";

grant truncate on table "public"."groups" to "anon";

grant update on table "public"."groups" to "anon";

grant delete on table "public"."groups" to "authenticated";

grant insert on table "public"."groups" to "authenticated";

grant references on table "public"."groups" to "authenticated";

grant select on table "public"."groups" to "authenticated";

grant trigger on table "public"."groups" to "authenticated";

grant truncate on table "public"."groups" to "authenticated";

grant update on table "public"."groups" to "authenticated";

grant delete on table "public"."groups" to "service_role";

grant insert on table "public"."groups" to "service_role";

grant references on table "public"."groups" to "service_role";

grant select on table "public"."groups" to "service_role";

grant trigger on table "public"."groups" to "service_role";

grant truncate on table "public"."groups" to "service_role";

grant update on table "public"."groups" to "service_role";

grant delete on table "public"."transactions" to "anon";

grant insert on table "public"."transactions" to "anon";

grant references on table "public"."transactions" to "anon";

grant select on table "public"."transactions" to "anon";

grant trigger on table "public"."transactions" to "anon";

grant truncate on table "public"."transactions" to "anon";

grant update on table "public"."transactions" to "anon";

grant delete on table "public"."transactions" to "authenticated";

grant insert on table "public"."transactions" to "authenticated";

grant references on table "public"."transactions" to "authenticated";

grant select on table "public"."transactions" to "authenticated";

grant trigger on table "public"."transactions" to "authenticated";

grant truncate on table "public"."transactions" to "authenticated";

grant update on table "public"."transactions" to "authenticated";

grant delete on table "public"."transactions" to "service_role";

grant insert on table "public"."transactions" to "service_role";

grant references on table "public"."transactions" to "service_role";

grant select on table "public"."transactions" to "service_role";

grant trigger on table "public"."transactions" to "service_role";

grant truncate on table "public"."transactions" to "service_role";

grant update on table "public"."transactions" to "service_role";


  create policy "Enable users to view their own data only"
  on "public"."accounts"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."categories"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."currencies"
  as permissive
  for select
  to public
using (true);



  create policy "Enable users to view their own data only"
  on "public"."groups"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."transactions"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));


CREATE TRIGGER before_update_account_trigger BEFORE UPDATE ON public.accounts FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column();

CREATE TRIGGER before_update_transaction_trigger BEFORE UPDATE ON public.transactions FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column();

CREATE TRIGGER set_account_currency_trigger BEFORE INSERT ON public.transactions FOR EACH ROW EXECUTE FUNCTION public.set_transaction_account_currency();

CREATE TRIGGER create_user_trigger AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_default_user_categories();


